[build]
builder = "NIXPACKS"
buildCommand = "npm run api:build"

[deploy]
startCommand = "npm run api:start"
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[postgres]
database = "railway" 