[build]
builder = "NIXPACKS"
buildCommand = "npm run api:build"

[deploy]
startCommand = "npm run api:start"
healthcheckPath = "/healthz"
healthcheckTimeout = 900
healthcheckDisabled = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[postgres]
database = "railway"

[environments.production]
NODE_ENV = "production"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
FRONTEND_URL = "https://pasha-frontend.vercel.app" 