[build]
builder = "NIXPACKS"
buildCommand = "npm run api:build"

[deploy]
startCommand = "npm run api:start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
healthcheckDisabled = false
restartPolicyType = "on_failure"

[postgres]
database = "railway" 