[build]
builder = "NIXPACKS"
buildCommand = "npm run api:build"

[deploy]
startCommand = "npm run api:start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
healthcheckDisabled = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[postgres]
database = "railway"

[environments.production]
NODE_ENV = "production"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
NODE_OPTIONS = "--max-old-space-size=512"
RAILWAY_STATIC_URL = "true" 