[build]
builder = "NIXPACKS"
buildCommand = "npm run api:build"

[deploy]
startCommand = "npm run api:start"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckDisabled = true
restartPolicyType = "on_failure"

[postgres]
database = "railway" 